class StatsHelper {
  static String confirmedCases =
      '#main > div > div > div > section.elementor-section.elementor-top-section.elementor-element.elementor-element-4953d8ff.elementor-section-full_width.elementor-section-height-default.elementor-section-height-default > div.elementor-container.elementor-column-gap-no > div > div > div > div > section.elementor-section.elementor-inner-section.elementor-element.elementor-element-6f98bbd0.elementor-section-boxed.elementor-section-height-default.elementor-section-height-default > div > div > div.elementor-column.elementor-col-33.elementor-inner-column.elementor-element.elementor-element-59e8c78f > div > div > div.elementor-element.elementor-element-c11c81c.elementor-widget.elementor-widget-heading > div > p';
  static String tested =
      '#main > div > div > div > section.elementor-element.elementor-element-4953d8ff.elementor-section-full_width.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-top-section > div.elementor-container.elementor-column-gap-no > div > div > div > div > section.elementor-element.elementor-element-3847b70.elementor-hidden-desktop.elementor-hidden-tablet.elementor-section-boxed.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-inner-section > div > div > div.elementor-element.elementor-element-53a7df09.elementor-column.elementor-col-16.elementor-inner-column > div > div > div.elementor-element.elementor-element-68c970ce.elementor-widget.elementor-widget-heading > div > p';
  static String deaths =
      '#main > div > div > div > section.elementor-element.elementor-element-4953d8ff.elementor-section-full_width.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-top-section > div.elementor-container.elementor-column-gap-no > div > div > div > div > section.elementor-element.elementor-element-6f98bbd0.elementor-section-boxed.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-inner-section > div > div > div.elementor-element.elementor-element-571da723.elementor-column.elementor-col-33.elementor-inner-column > div > div > div.elementor-element.elementor-element-b99363d.elementor-widget.elementor-widget-heading > div > p';
  static String tested24hours =
      '#main > div > div > div > section.elementor-element.elementor-element-4953d8ff.elementor-section-full_width.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-top-section > div.elementor-container.elementor-column-gap-no > div > div > div > div > section.elementor-element.elementor-element-234f11a9.elementor-hidden-phone.elementor-section-boxed.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-inner-section > div > div > div.elementor-element.elementor-element-d7ca9c7.elementor-column.elementor-col-16.elementor-inner-column > div > div > div.elementor-element.elementor-element-39f31511.elementor-widget.elementor-widget-heading > div > p';
  static String infected24hours =
      '#main > div > div > div > section.elementor-element.elementor-element-4953d8ff.elementor-section-full_width.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-top-section > div.elementor-container.elementor-column-gap-no > div > div > div > div > section.elementor-element.elementor-element-234f11a9.elementor-hidden-phone.elementor-section-boxed.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-inner-section > div > div > div.elementor-element.elementor-element-71ed3c8f.elementor-column.elementor-col-16.elementor-inner-column > div > div > div.elementor-element.elementor-element-7275fa4a.elementor-widget.elementor-widget-heading > div > p';
  static String deceased24hours =
      '#main > div > div > div > section.elementor-element.elementor-element-4953d8ff.elementor-section-full_width.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-top-section > div.elementor-container.elementor-column-gap-no > div > div > div > div > section.elementor-element.elementor-element-234f11a9.elementor-hidden-phone.elementor-section-boxed.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-inner-section > div > div > div.elementor-element.elementor-element-f7b4ffe.elementor-column.elementor-col-16.elementor-inner-column > div > div > div.elementor-element.elementor-element-482359d.elementor-widget.elementor-widget-heading > div > p';
  static String hospitalized =
      '#main > div > div > div > section.elementor-element.elementor-element-4953d8ff.elementor-section-full_width.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-top-section > div.elementor-container.elementor-column-gap-no > div > div > div > div > section.elementor-element.elementor-element-234f11a9.elementor-hidden-phone.elementor-section-boxed.elementor-section-height-default.elementor-section-height-default.elementor-section.elementor-inner-section > div > div > div.elementor-element.elementor-element-57c69ff4.elementor-column.elementor-col-16.elementor-inner-column > div > div > div.elementor-element.elementor-element-571cb025.elementor-widget.elementor-widget-heading > div > p';
  static String patientsOnVentilators =
      '#main > div > div > div > section.elementor-section.elementor-top-section.elementor-element.elementor-element-4953d8ff.elementor-section-full_width.elementor-section-height-default.elementor-section-height-default > div.elementor-container.elementor-column-gap-no > div > div > div > div > section.elementor-section.elementor-inner-section.elementor-element.elementor-element-3847b70.elementor-hidden-desktop.elementor-hidden-tablet.elementor-section-boxed.elementor-section-height-default.elementor-section-height-default > div > div > div.elementor-column.elementor-col-16.elementor-inner-column.elementor-element.elementor-element-0351a70 > div > div > div.elementor-element.elementor-element-5344cb8.elementor-widget.elementor-widget-heading > div > p';
  static String source = 'https://covid19.rs';
  static String path = '/homepage-english/';
}
